# Generated by Django 4.1.2 on 2022-10-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientlog",
            name="may_contact",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("tbd", "To be determined")],
                default="tbd",
                max_length=15,
                verbose_name="Has the patient agreed to be contacted prior to consent?",
            ),
        ),
        migrations.AddField(
            model_name="patientlog",
            name="may_contact",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("tbd", "To be determined")],
                default="tbd",
                max_length=15,
                verbose_name="Has the patient agreed to be contacted prior to consent?",
            ),
        ),
    ]
