# Generated by Django 4.1.2 on 2022-10-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="art_adherent",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="in regular attendance for care",
                max_length=15,
                verbose_name="Is the patient considered to be adherent to treatment over the last 6 months",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="art_stable",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="considered by the clinical team not to have any complications/co-infections or that these are well managed.",
                max_length=15,
                verbose_name="Is the patient considered to be stable on treatment ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="art_unchanged_3m",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="Meaning no modifications to the type of medication and dose for at least 3 months",
                max_length=15,
                verbose_name="Has the patient been on the same anti-retroviral therapy for at least 3 months",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="dm_complications",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Does the patient suffer from any complications of diabetes that are unmanaged or uncontrolled.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="dm_dx_6m",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Was the initial diagnosis made more than 6 months ago",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="hiv_dx_6m",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Was the initial diagnosis made more than 6 months ago",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="htn_complications",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Does the patient suffer from any complications of hypertension that are unmanaged or uncontrolled.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="htn_dx_6m",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Was the initial diagnosis made more than 6 months ago",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="art_adherent",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="in regular attendance for care",
                max_length=15,
                verbose_name="Is the patient considered to be adherent to treatment over the last 6 months",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="art_stable",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="considered by the clinical team not to have any complications/co-infections or that these are well managed.",
                max_length=15,
                verbose_name="Is the patient considered to be stable on treatment ",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="art_unchanged_3m",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="Meaning no modifications to the type of medication and dose for at least 3 months",
                max_length=15,
                verbose_name="Has the patient been on the same anti-retroviral therapy for at least 3 months",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="dm_complications",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Does the patient suffer from any complications of diabetes that are unmanaged or uncontrolled.",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="dm_dx_6m",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Was the initial diagnosis made more than 6 months ago",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="hiv_dx_6m",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Was the initial diagnosis made more than 6 months ago",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="htn_complications",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Does the patient suffer from any complications of hypertension that are unmanaged or uncontrolled.",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="htn_dx_6m",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Was the initial diagnosis made more than 6 months ago",
            ),
        ),
    ]
