# Generated by Django 4.1.2 on 2022-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0002_historicalpatientlog_may_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientlog",
            name="consent_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Auto populated when consent form is complete", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientlog",
            name="consent_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Auto populated when consent form is complete", null=True
            ),
        ),
    ]
