# Generated by Django 3.2.14 on 2022-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intecomm_screening', '0002_auto_20220719_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscreeningpartone',
            name='eligible_part_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('tbd', 'To be determined')], default='tbd', editable=False, help_text='system calculated value', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalscreeningpartone',
            name='eligible_part_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('tbd', 'To be determined')], default='tbd', editable=False, help_text='system calculated value', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalscreeningpartone',
            name='reasons_ineligible_part_one',
            field=models.TextField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalscreeningpartone',
            name='reasons_ineligible_part_two',
            field=models.TextField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalscreeningparttwo',
            name='eligible_part_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('tbd', 'To be determined')], default='tbd', editable=False, help_text='system calculated value', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalscreeningparttwo',
            name='eligible_part_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('tbd', 'To be determined')], default='tbd', editable=False, help_text='system calculated value', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalscreeningparttwo',
            name='reasons_ineligible_part_one',
            field=models.TextField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalscreeningparttwo',
            name='reasons_ineligible_part_two',
            field=models.TextField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='eligible_part_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('tbd', 'To be determined')], default='tbd', editable=False, help_text='system calculated value', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='eligible_part_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('tbd', 'To be determined')], default='tbd', editable=False, help_text='system calculated value', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='reasons_ineligible_part_one',
            field=models.TextField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='reasons_ineligible_part_two',
            field=models.TextField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='eligible_part_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('tbd', 'To be determined')], default='tbd', editable=False, help_text='system calculated value', max_length=15),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='eligible_part_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('tbd', 'To be determined')], default='tbd', editable=False, help_text='system calculated value', max_length=15),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='reasons_ineligible_part_one',
            field=models.TextField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='reasons_ineligible_part_two',
            field=models.TextField(editable=False, max_length=150, null=True),
        ),
    ]
