# Generated by Django 4.1.2 on 2022-11-01 16:10
import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    patient_log = apps.get_model("intecomm_screening", "patientlog")
    for row in patient_log._default_manager.all():
        row.patient_log_identifier = uuid.uuid4()
        row.save(update_fields=["patient_log_identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0004_historicalpatientlog_patient_log_identifier_and_more"),
    ]

    operations = [migrations.RunPython(gen_uuid)]
