# Generated by Django 4.1.2 on 2022-10-28 18:39

from django.db import migrations
import edc_model_fields.fields.initials_field


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0004_patientlog_subject_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientlog",
            name="initials",
            field=edc_model_fields.fields.initials_field.InitialsField(
                default="ZZ",
                help_text="Type 2-3 letters, all in uppercase and no spaces",
                max_length=3,
                verbose_name="Initials",
            ),
            preserve_default=False,
        ),
    ]
