# Generated by Django 4.1.2 on 2022-11-01 16:13
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0005_auto_20221101_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientlog",
            name="patient_log_identifier",
            field=models.CharField(
                default=uuid.uuid4,
                unique=True,
                max_length=36,
            ),
        ),
    ]
