# Generated by Django 4.1.2 on 2022-10-29 01:06

from django.db import migrations, models
import edc_utils.date


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0006_alter_patientlog_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterModelOptions(
            name="patientgroup",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
            },
        ),
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="report_datetime",
            field=models.DateTimeField(default=edc_utils.date.get_utcnow),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="report_datetime",
            field=models.DateTimeField(default=edc_utils.date.get_utcnow),
        ),
    ]
