# Generated by Django 4.1.2 on 2022-11-01 23:53

from django.db import migrations, models
import edc_sites.models
import intecomm_screening.models.patient_log
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0006_auto_20221101_1913"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="patientlog",
            managers=[
                ("on_site", edc_sites.models.CurrentSiteManager()),
                ("objects", intecomm_screening.models.patient_log.PatientLogManager()),
            ],
        ),
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="ratio",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="ratio",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalpatientlog",
            name="patient_log_identifier",
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=36),
        ),
    ]
