# Generated by Django 4.1.2 on 2022-10-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0007_delete_location_alter_patientgroup_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientgroup",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientgroup",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientgroup",
            name="patients",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"consented": False, "eligible": True},
                null=True,
                to="intecomm_screening.subjectscreening",
            ),
        ),
    ]
