# Generated by Django 4.1.2 on 2022-10-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0008_alter_historicalpatientgroup_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpatientlog",
            name="patient_group",
        ),
        migrations.RemoveField(
            model_name="patientlog",
            name="patient_group",
        ),
        migrations.AlterField(
            model_name="patientgroup",
            name="patients",
            field=models.ManyToManyField(blank=True, to="intecomm_screening.patientlog"),
        ),
    ]
