# Generated by Django 4.1.2 on 2022-11-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0008_patientcall_historicalpatientcall"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientlog",
            name="call_attempts",
            field=models.IntegerField(blank=True, default=0, help_text="auto-updated"),
        ),
        migrations.AddField(
            model_name="patientlog",
            name="call_attempts",
            field=models.IntegerField(blank=True, default=0, help_text="auto-updated"),
        ),
    ]
