# Generated by Django 4.1.2 on 2022-11-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0009_historicalpatientlog_call_attempts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpatientcall",
            name="next_appt_date",
        ),
        migrations.RemoveField(
            model_name="patientcall",
            name="next_appt_date",
        ),
    ]
