# Generated by Django 4.1.2 on 2022-10-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0010_remove_historicalsubjectscreening_ethnicity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="randomize",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Randomise now?",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="randomize",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Randomise now?",
            ),
        ),
    ]
