# Generated by Django 4.1.2 on 2022-11-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0010_remove_historicalpatientcall_next_appt_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientgroup",
            name="ratio",
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="patientgroup",
            name="ratio",
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
