# Generated by Django 4.1.2 on 2022-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0011_alter_historicalpatientgroup_ratio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientlog",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="patientlog",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientlog",
            name="first_health_talk",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("tbd", "To be determined")],
                default="tbd",
                max_length=15,
                verbose_name="Attended general health talk",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientlog",
            name="first_health_talk_date",
            field=models.DateField(blank=True, null=True, verbose_name="General talk date"),
        ),
        migrations.AlterField(
            model_name="historicalpatientlog",
            name="second_health_talk",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("tbd", "To be determined")],
                default="tbd",
                max_length=15,
                verbose_name="Attended sensitisation session",
            ),
        ),
        migrations.AlterField(
            model_name="patientlog",
            name="first_health_talk",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("tbd", "To be determined")],
                default="tbd",
                max_length=15,
                verbose_name="Attended general health talk",
            ),
        ),
        migrations.AlterField(
            model_name="patientlog",
            name="first_health_talk_date",
            field=models.DateField(blank=True, null=True, verbose_name="General talk date"),
        ),
        migrations.AlterField(
            model_name="patientlog",
            name="second_health_talk",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("tbd", "To be determined")],
                default="tbd",
                max_length=15,
                verbose_name="Attended sensitisation session",
            ),
        ),
    ]
