# Generated by Django 4.1.2 on 2022-11-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0012_historicalpatientlog_gender_patientlog_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="screening_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Screening ID"
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="screening_identifier",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Screening ID"
            ),
        ),
    ]
