# Generated by Django 4.1.2 on 2022-11-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_lists", "0003_healthfacilities_and_more"),
        ("intecomm_screening", "0014_healthtalklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthtalklog",
            name="health_facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="intecomm_lists.healthfacilities",
                verbose_name="Health facility type",
            ),
        ),
    ]
