# Generated by Django 4.1.2 on 2022-11-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0015_alter_healthtalklog_health_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthtalklog",
            name="health_facility_name",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="healthtalklog",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
