# Generated by Django 4.1.7 on 2023-05-01 19:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_screening", "0021_idenfifierformat"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientlog",
            name="filing_identifier",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="A sequential number to label a manual patient file",
                max_length=36,
                null=True,
                verbose_name="File number",
            ),
        ),
        migrations.AddField(
            model_name="patientlog",
            name="filing_identifier",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="A sequential number to label a manual patient file",
                max_length=36,
                null=True,
                verbose_name="File number",
            ),
        ),
    ]
