# Generated by Django 4.2.7 on 2023-12-04 22:19

from django.db import migrations, models
import edc_utils.date


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_screening", "0062_auto_20230831_0032"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consentrefusal",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Consent Refusal",
                "verbose_name_plural": "Consent Refusals",
            },
        ),
        migrations.AlterModelOptions(
            name="healthtalklog",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Health talk log",
                "verbose_name_plural": "Health talk logs",
            },
        ),
        migrations.AlterModelOptions(
            name="oldhealthfacility",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Health Facility",
                "verbose_name_plural": "Health Facilities",
            },
        ),
        migrations.AlterModelOptions(
            name="patientcall",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ["report_datetime"],
                "verbose_name": "Patient Call",
                "verbose_name_plural": "Patient Calls",
            },
        ),
        migrations.AlterModelOptions(
            name="patientlog",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Patient Log",
                "verbose_name_plural": "Patient Log",
            },
        ),
        migrations.AlterModelOptions(
            name="patientlogreportprinthistory",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Patient Log Report Print History",
                "verbose_name_plural": "Patient Log Report Print History",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectscreening",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Subject Screening",
                "verbose_name_plural": "Subject Screening",
            },
        ),
        migrations.AlterUniqueTogether(
            name="patientlog",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subjectscreening",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="consentrefusal",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="consentrefusal",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="healthtalklog",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="healthtalklog",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsentrefusal",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsentrefusal",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalhealthtalklog",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalhealthtalklog",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicaloldhealthfacility",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicaloldhealthfacility",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientcall",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientcall",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientlog",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientlog",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientlogug",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientlogug",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectscreeningug",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectscreeningug",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="oldhealthfacility",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="oldhealthfacility",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="patientcall",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="patientcall",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="patientlog",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="patientlog",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="patientlogreportprinthistory",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="patientlogreportprinthistory",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientcall",
            name="report_datetime",
            field=models.DateTimeField(db_index=True, default=edc_utils.date.get_utcnow),
        ),
        migrations.AlterField(
            model_name="patientcall",
            name="report_datetime",
            field=models.DateTimeField(db_index=True, default=edc_utils.date.get_utcnow),
        ),
        migrations.AddIndex(
            model_name="consentrefusal",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_sc_modifie_810e6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrefusal",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_sc_user_mo_5255fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthtalklog",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_sc_modifie_d8ef96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthtalklog",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_sc_user_mo_eea0dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="oldhealthfacility",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_sc_modifie_2d68e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oldhealthfacility",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_sc_user_mo_6c3bd9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientcall",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_sc_modifie_4901ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientcall",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_sc_user_mo_8f9412_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientlog",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_sc_modifie_fa49a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientlog",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_sc_user_mo_08d139_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientlogreportprinthistory",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_sc_modifie_891a97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientlogreportprinthistory",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_sc_user_mo_7c6828_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectscreening",
            index=models.Index(
                fields=["subject_identifier"], name="intecomm_sc_subject_7056ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectscreening",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_sc_modifie_824618_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectscreening",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_sc_user_mo_54a1bf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientlog",
            constraint=models.UniqueConstraint(
                fields=("legal_name", "initials"),
                name="intecomm_screening_patientlog_legal_n_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectscreening",
            constraint=models.UniqueConstraint(
                fields=("legal_name", "initials"),
                name="intecomm_screening_subjectscreening_legal_n_uniq",
            ),
        ),
    ]
