# Generated by Django 6.0 on 2025-01-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0073_data_fix_812_gender_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientlog",
            name="filing_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-populated when form is saved. &lt;BR&gt;This is a sequential-like identifier to label this patient&#x27;s paper file",
                max_length=36,
                verbose_name="Filing number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientlog",
            name="patient_log_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-populated when form is saved. &lt;BR&gt;You may prefer to use the FILING NUMBER. &lt;BR&gt;This identifier is replaced by the &#x27;screening identifier&#x27; if the patient screens for the INTECOMM trial",
                max_length=36,
                verbose_name="Patient Log Reference",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientlogug",
            name="filing_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-populated when form is saved. &lt;BR&gt;This is a sequential-like identifier to label this patient&#x27;s paper file",
                max_length=36,
                verbose_name="Filing number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientlogug",
            name="patient_log_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-populated when form is saved. &lt;BR&gt;You may prefer to use the FILING NUMBER. &lt;BR&gt;This identifier is replaced by the &#x27;screening identifier&#x27; if the patient screens for the INTECOMM trial",
                max_length=36,
                verbose_name="Patient Log Reference",
            ),
        ),
        migrations.AlterField(
            model_name="patientlog",
            name="filing_identifier",
            field=models.CharField(
                blank=True,
                help_text="Auto-populated when form is saved. &lt;BR&gt;This is a sequential-like identifier to label this patient&#x27;s paper file",
                max_length=36,
                unique=True,
                verbose_name="Filing number",
            ),
        ),
        migrations.AlterField(
            model_name="patientlog",
            name="patient_log_identifier",
            field=models.CharField(
                blank=True,
                help_text="Auto-populated when form is saved. &lt;BR&gt;You may prefer to use the FILING NUMBER. &lt;BR&gt;This identifier is replaced by the &#x27;screening identifier&#x27; if the patient screens for the INTECOMM trial",
                max_length=36,
                unique=True,
                verbose_name="Patient Log Reference",
            ),
        ),
    ]
