# Generated by Django 4.1.2 on 2022-11-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_consent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="ethnicity",
            field=models.CharField(
                default="black",
                editable=False,
                help_text="fromm screening",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="ethnicity",
            field=models.CharField(
                default="black",
                editable=False,
                help_text="fromm screening",
                max_length=15,
                null=True,
            ),
        ),
    ]
