# Generated by Django 4.2.1 on 2023-07-06 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_consent", "0009_alter_subjectconsent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectreconsent",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Subject re-consent",
            },
        ),
    ]
