import pandas as pd
from edc_action_item.constants import ACTION_ITEM_COLUMNS
from edc_model_to_dataframe.constants import SYSTEM_COLUMNS
from edc_pdutils.dataframes import get_crf

mappings = {
    "A friend also reports that when Cal": "unknown",
    "ATTENDEDED AT FACILITY": "attended_facility",
    "Admitted": "admitted_to_hospital",
    "Admitted  Muhimbili hospital": "admitted_to_hospital",
    "Admitted for leg surgery": "admitted_to_hospital",
    "Already attached facility arm": "attended_facility",
    "Appointment at another hospital": "attending_elsewhere",
    "Appointment date falls on weekend": "unknown",
    "Attended at another facility": "attending_elsewhere",
    "Attended at different clinic": "attending_elsewhere",
    "Attended clinic on 17th November": "attending_elsewhere",
    "Attending IAC at the facility": "attending_elsewhere",
    "Attending other facility": "attending_elsewhere",
    "Away at work": "working_schooling",
    "Away attending treatment for swolle": "too_sick",
    "BUSY AT WORK": "working_schooling",
    "BUSY SCHEDULE": "too_busy",
    "Back to facility for medication": "drug_refill_done_earlier_or_not_needed",
    "Bad weather condition": "weather_condition",
    "Bad weather, it was raining all da.": "weather_condition",
    "Busy": "too_busy",
    "Busy at work": "working_schooling",
    "Busy schedule": "too_busy",
    "Busy taking care of her mother who": "too_busy",
    "Busy with work": "working_schooling",
    "Busy work schedule": "working_schooling",
    "Busy working schedule": "working_schooling",
    "Buying drugs on street phamacies": "drug_refill_done_earlier_or_not_needed",
    "Came late": "arrived_to_late",
    "Caring for her sick relative": "family_obligation",
    "Change of address": "moved",
    "Congested clinic": "clinic_too_busy",
    "Consultation fee was unissue": "no_money",
    "DRUG REFIL WAS DONE 25/7": "drug_refill_done_earlier_or_not_needed",
    "Death report": "death_report",
    "Did not answer the calls": "no_contact",
    "Did not have money for bus fare.": "no_money",
    "Did not have money for drugs": "no_money",
    "Didn't have the study card": "lost_study_card",
    "Do not have bus fare": "no_money",
    "Do not have time this month": "too_busy",
    "Drug availability": "heard_no_drug_supply",
    "Drugs availability": "heard_no_drug_supply",
    "Drugs refilled for 6 months": "drug_refill_done_earlier_or_not_needed",
    "Due to ctc date": "blocked_by_ctc_date",
    "Economic dificulities": "no_money",
    "Employees doesn't grant her permiss": "working_schooling",
    "Expired imsurance": "insurance_issue_or_expired",
    "Expired insurance": "insurance_issue_or_expired",
    "Expired. Insurance": "insurance_issue_or_expired",
    "FEELING WELL": "feels_well",
    "FELT BETTER": "feels_well",
    "Facility care": "attended_facility",
    "Family issues": "family_emergency",
    "Financial challenges": "no_money",
    "Financial difficulties": "no_money",
    "Got accident on her way to the comm": "accident_on_route",
    "Got caught up on the way": "too_busy",
    "Got his refill from the pharmacy": "drug_refill_done_earlier_or_not_needed",
    "HAD DRUGS": "drug_refill_done_earlier_or_not_needed",
    "HAS PATIENT AT HOME": "family_emergency",
    "Had ART pills at home": "drug_refill_done_earlier_or_not_needed",
    "Had a bussiness trip": "working_schooling",
    "Had a patient in Mulago hospital.": "family_emergency",
    "Had a sick daughter": "family_emergency",
    "Had an accident,currently immobile": "injured_not_able_to_travel",
    "Had drug": "drug_refill_done_earlier_or_not_needed",
    "Had drug refill gor 6 months": "drug_refill_done_earlier_or_not_needed",
    "Had drugs": "drug_refill_done_earlier_or_not_needed",
    "Had enough drugs": "drug_refill_done_earlier_or_not_needed",
    "Had gone for another appointment": "too_busy",
    "Had got his refill from the pharma": "drug_refill_done_earlier_or_not_needed",
    "Had got his refill from the pharmac": "drug_refill_done_earlier_or_not_needed",
    "Had her pills at home.": "drug_refill_done_earlier_or_not_needed",
    "Had medication": "drug_refill_done_earlier_or_not_needed",
    "Had no escoter": "lack_of_transport",
    "Had no escotter": "lack_of_transport",
    "Had no money": "no_money",
    "Had no money for clinic": "no_money",
    "Had no phone": "no_contact",
    "Had no transport fair to facility": "no_money",
    "Had other engagements": "too_busy",
    "Had pills at home": "drug_refill_done_earlier_or_not_needed",
    "Had pills at home.": "drug_refill_done_earlier_or_not_needed",
    "Had refill for other 2 months": "drug_refill_done_earlier_or_not_needed",
    "Had shifted to Onother location": "attending_elsewhere",
    "Had some drugs": "drug_refill_done_earlier_or_not_needed",
    "Had the pills at home": "drug_refill_done_earlier_or_not_needed",
    "Had travelled the village": "travelling",
    "Had travelled to the village": "travelling",
    "Had travelled to village": "travelling",
    "Has a sick daughter": "family_emergency",
    "Has a sick patient": "family_emergency",
    "Has personal  issues with the VHT": "personal_issue_with_vht",
    "Has pills at home": "drug_refill_done_earlier_or_not_needed",
    "Has wrangles with VHT": "personal_issue_with_vht",
    "Have another clinc today": "too_busy",
    "He did not pick": "no_contact",
    "He got better": "feels_well",
    "He has personal issues with the VHT": "personal_issue_with_vht",
    "He have more medication": "drug_refill_done_earlier_or_not_needed",
    "He relocated to HOIMA district": "moved",
    "He still has pills": "drug_refill_done_earlier_or_not_needed",
    "Health Insuarance expired": "insurance_issue_or_expired",
    "Health insurance  problems": "insurance_issue_or_expired",
    "Husband got a new job": "moved",
    "Husband relocated to luwero": "moved",
    "I have leg pain": "unwell",
    "IDD day": "idd_day",
    "IN ANOTHER RESEACH STUDY": "too_busy",
    "Insurance expired": "insurance_issue_or_expired",
    "Insurance were not valid": "insurance_issue_or_expired",
    "Invalid missed appointment": "invalid_missed_appointment",
    "LACK OF DRUGS  AT HEALTH FACILITY": "heard_no_drug_supply",
    "Lack of drugs at the facility": "heard_no_drug_supply",
    "Makes the phone busy": "no_contact",
    "NHIF patient": "attended_facility",
    "NHIF patient attend facility": "attended_facility",
    "NHIF patient attending facility": "attended_facility",
    "NHIF patient attwnding facility": "attended_facility",
    "NHIF patient qtyending facility": "attended_facility",
    "NHIF patient will attend facility": "attended_facility",
    "NHIF patient will come to facility": "attended_facility",
    "NHIF patients  come to facility": "attended_facility",
    "Need to be remainded": "unknown",
    "Never had club money for drugs": "no_money",
    "Nhif patient attending facility": "attended_facility",
    "Nhif patient will attend facility": "attended_facility",
    "No  money for drugs": "no_money",
    "No battery   for her phone and  far": "no_contact",
    "No consultation fee": "no_money",
    "No longer want to come to facility": "attending_elsewhere",
    "No longer want to come to health ce": "attending_elsewhere",
    "No money for bus fare": "no_money",
    "No money for clinic": "no_money",
    "No money for consultation fee": "no_money",
    "No money to attend clinic": "no_money",
    "No money to come to clinic": "no_money",
    "No time today": "too_busy",
    "Not appointed for any refill": "drug_refill_done_earlier_or_not_needed",
    "Not available through phone calls": "no_money",
    "Not interested to participate": "not_interested_in_study",
    "Not picking calls": "no_contact",
    "Not picking up": "no_contact",
    "Not picking up a call": "no_contact",
    "Not reachable": "no_contact",
    "Not reachable on phone call": "no_contact",
    "Not willing to come": "too_busy",
    "Not willing to come. Gave no reason": "too_busy",
    "Nursing hospitalised mom": "family_emergency",
    "Nursing hospitalized child": "family_emergency",
    "Nursing hospitalized mom": "family_emergency",
    "Other appointment at another hospit": "too_busy",
    "PATIENT HAD OTHER ENGAGEMENTS": "too_busy",
    "PREFERS TO COME ON HER DRUG REFILL": "drug_refill_done_earlier_or_not_needed",
    "Participant got an accident": "injured_not_able_to_travel",
    "Participant got anew job and reloca": "moved",
    "Participant has a personal issue VH": "personal_issue_with_vht",
    "Participant left the country to UAE": "moved",
    "Participant was involved in an inci": "injured_not_able_to_travel",
    "Participant was represented": "unknown",
    "Participant went took her son for P": "too_busy",
    "Participant's appointment is not du": "too_busy",
    "Patient attended different clinic": "attending_elsewhere",
    "Patient attending facility clinic": "attended_facility",
    "Patient has no bus fair": "no_money",
    "Patient has no consultation fee": "no_money",
    "Patient have drugs": "drug_refill_done_earlier_or_not_needed",
    "Patient relocated": "moved",
    "Patient transferred": "moved",
    "Promised to come but never showed u": "too_busy",
    "REACHED LATE AT THE MEETING POINT": "too_busy",
    "REFFERED TO KIRUDDU HOSPITAL": "referred_to_hospital",
    "REFILLED DRUG AT NEAR FACILITY": "drug_refill_done_earlier_or_not_needed",
    "REFILLED DRUG AT NEARFACILITY": "drug_refill_done_earlier_or_not_needed",
    "Rained heavily": "weather_condition",
    "Receiving care from another facilit": "attended_facility",
    "Recieved care from not kiswa": "attending_elsewhere",
    "Refilled her medication 4th  Nov": "drug_refill_done_earlier_or_not_needed",
    "Relocated": "moved",
    "Relocated and is far from the facil": "moved",
    "Relocated to Bushenyi": "moved",
    "Relocated to HOIMA district": "moved",
    "Relocated to Luwero": "moved",
    "Relocated to up country": "moved",
    "Relocated,  to be exited": "moved",
    "Represented by the husband": "husband_represents",
    "Road accident": "injured_not_able_to_travel",
    "Road transport accident": "injured_not_able_to_travel",
    "SAE": "too_sick",
    "SHE FELT BETTER": "feels_well",
    "SHE FELT WELL": "feels_well",
    "SHE PREFERS TO AFTER 3 MONTHS": "too_busy",
    "SHE WAS AT WORK": "working_schooling",
    "SHE WAS DONE CESEREAN DELIVERY.": "gave_birth",
    "Says the hospital doesn’t have drug": "heard_no_drug_supply",
    "Self medication at home": "drug_refill_done_earlier_or_not_needed",
    "Self referral to another facility": "referred",
    "Self transfer to facility": "referred_to_facility",
    "Self transfer to the facility": "referred_to_facility",
    "Self transferred to tegeta": "moved",
    "She got a better physician.": "attending_elsewhere",
    "She had to go for work": "working_schooling",
    "She has appointment to another hosp": "attending_elsewhere",
    "She has medication already": "drug_refill_done_earlier_or_not_needed",
    "She has more medications": "drug_refill_done_earlier_or_not_needed",
    "She have drugs for months she don't": "drug_refill_done_earlier_or_not_needed",
    "She is an HIV participant who prefe": "attended_facility",
    "She is busy today, no time to come": "too_busy",
    "She is reported to be sick": "too_sick",
    "She is still sick": "too_sick",
    "She said she healed.": "feels_well",
    "She travelled to Saudi arabia for w": "travelling",
    "She was admitted at Iran hospital": "admitted_to_hospital",
    "She went to the village": "too_busy",
    "Sick": "too_sick",
    "Skipped visit not missed": "skipped_as_per_protocol",
    "Skipped visit, not a missed visit": "skipped_as_per_protocol",
    "Still Had drugs gor 2months": "drug_refill_done_earlier_or_not_needed",
    "Still had drugs for 3 months": "drug_refill_done_earlier_or_not_needed",
    "Still had drugs for 4months": "drug_refill_done_earlier_or_not_needed",
    "Still had pills at home": "drug_refill_done_earlier_or_not_needed",
    "Still has ART pills at home": "drug_refill_done_earlier_or_not_needed",
    "Still has drugs": "drug_refill_done_earlier_or_not_needed",
    "Still has pills at home": "drug_refill_done_earlier_or_not_needed",
    "Still has pills at home.": "drug_refill_done_earlier_or_not_needed",
    "Still have medicine": "drug_refill_done_earlier_or_not_needed",
    "Stopped Medication": "stopped_medication",
    "TB patient Transferred to the facil": "tb",
    "TB patient discharged from the faci": "tb",
    "THERE WAS NO CLINICIAN AT THE FACIL": "heard_no_clinician_at_facily",
    "THINKS NO DRUGS AT HOSPITAL": "heard_no_drugs_at_hospital",
    "TRANSFERED TO OTHER CLINIC": "referred_to_other_facility",
    "Taking care of a patient": "too_busy",
    "Taking care of her sick children": "too_busy",
    "The appointment date was less than": "unknown",
    "The facility didn't have drugs.": "heard_no_drugs_at_hospital",
    "They will attend facility for drug": "attended_facility",
    "This visit is not her next appointm": "unknown",
    "Too much rain": "weather_condition",
    "Took her child to school": "too_busy",
    "Transfer to the facility": "attended_facility",
    "Transfered to another facility": "attending_elsewhere",
    "Transferred to other facility": "attending_elsewhere",
    "Unable to walk to the hospital": "unwell",
    "Unknown": "unknown",
    "Unstable,": "too_sick",
    "WAS ENGAGED IN OTHER ACTIVITIES": "too_busy",
    "Waiting for CHF to be ready": "insurance_issue_or_expired",
    "Waiting to get CHF insurance": "insurance_issue_or_expired",
    "Wanted to do ECHO ,": "unknown",
    "Was busy": "too_busy",
    "Was buying drugs street phamacies": "drug_refill_done_earlier_or_not_needed",
    "Was in a hurry, could not wait.": "too_busy",
    "Went to another health facility": "attending_elsewhere",
    "Will attend facility  care": "attended_facility",
    "Will attend facility on Friday": "too_busy",
    "Wrong appointment": "unknown",
    "admitted to Bagamoyo hospital": "admitted_to_hospital",
    "admitted to ocean road hospital": "admitted_to_hospital",
    "attending to a sick relative": "family_emergency",
    "attending to her sick child": "family_emergency",
    "bad weather": "weather_condition",
    "busy at work": "working_schooling",
    "busy schedule": "too_busy",
    "busy working": "working_schooling",
    "changed  place of care": "moved",
    "defaults intentionally": "unknown",
    "did not attend": "too_busy",
    "did not have money to travel": "no_money",
    "do not have money for transportatio": "no_money",
    "do not have time": "too_busy",
    "do not have time this month": "too_busy",
    "don't have money for transportation": "no_money",
    "expired insurance": "insurance_issue_or_expired",
    "family issues": "family_emergency",
    "had a terrible cough and  fever": "too_sick",
    "had other personal engagements": "too_busy",
    "he had etra pills": "drug_refill_done_earlier_or_not_needed",
    "he had operation appointment": "too_sick",
    "in mulago for ulcer for ulcers trea": "admitted_to_hospital",
    "insurance has expired": "insurance_issue_or_expired",
    "lack of drugs at the facility": "heard_no_drugs_at_hospital",
    "no money for fare and Consultation": "no_money",
    "not picking up a call": "no_contact",
    "not reachable": "no_contact",
    "patient cant attend clinic alone": "lack_of_transport",
    "patient purchases drugs": "drug_refill_done_earlier_or_not_needed",
    "patient relocated": "moved",
    "phone not answered": "no_contact",
    "she  has medication": "drug_refill_done_earlier_or_not_needed",
    "she did not get an escort": "lack_of_transport",
    "she is doing well": "feels_well",
    "stilll has drugs": "drug_refill_done_earlier_or_not_needed",
    "time and lack of money for bus fare": "no_money",
    "travelled to dar es salaam": "travelling",
    "want to come to hospital first": "attended_facility",
    "was not reachable lost my phone": "no_contact",
    "weather cant walk in rain": "weather_condition",
    "weather its raining": "weather_condition",
}


def get_subject_visit_missed() -> pd.DataFrame:
    action_cols = [
        col
        for col in ACTION_ITEM_COLUMNS
        if col not in ["action_item_id", "parent_action_item_id", "related_action_item_id"]
    ] + ["action_item", "parent_action_item", "related_action_item"]
    df_visit_missed = (
        get_crf(
            "intecomm_subject.subjectvisitmissed",
            subject_visit_model="intecomm_subject.subjectvisit",
            normalize=True,
            localize=True,
            read_verbose=True,
            drop_sys_columns=True,
            drop_action_item_columns=True,
        )
        .query("reason=='missed'")
        .drop(columns=action_cols)
        .drop(columns=SYSTEM_COLUMNS)
        .drop(
            columns=["consent_model", "consent_version", "crf_status", "crf_status_comments"]
        )
        .sort_values(["subject_identifier", "visit_code"])
        .reset_index(drop=True)
    )

    df_visit_missed["missed_reasons_other"] = df_visit_missed["missed_reasons_other"].replace(
        mappings
    )
    df_visit_missed["missed_reasons_other"] = df_visit_missed[
        "missed_reasons_other"
    ].str.lower()
    df_visit_missed.loc[
        df_visit_missed["missed_reasons_other"].str.strip() == "", "missed_reasons_other"
    ] = pd.NA

    df_visit_missed["missed_reasons"] = df_visit_missed["missed_reasons"].str.replace(
        "OTHER", "", case=False
    )
    df_visit_missed["missed_reasons"] = (
        df_visit_missed["missed_reasons"].str.strip(", ").str.replace(r",+", ",", regex=True)
    )

    df_visit_missed.loc[
        df_visit_missed["missed_reasons"].str.strip() == "", "missed_reasons"
    ] = pd.NA

    df_visit_missed.loc[df_visit_missed["missed_reasons_other"].notna(), "missed_reasons"] = (
        df_visit_missed["missed_reasons"].fillna("").str.lower()
        + ","
        + df_visit_missed["missed_reasons_other"].str.lower()
    )

    df_visit_missed["missed_reasons"] = df_visit_missed["missed_reasons"].str.lstrip(",")
    return df_visit_missed
