# Generated by Django 4.1.2 on 2022-11-29 01:15

from django.db import migrations, models
import edc_model.validators.date


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_subject", "0003_malariatest_historicalmalariatest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicalreviewbaseline",
            name="dm_test_estimated_datetime",
        ),
        migrations.RemoveField(
            model_name="clinicalreviewbaseline",
            name="hiv_test_estimated_datetime",
        ),
        migrations.RemoveField(
            model_name="clinicalreviewbaseline",
            name="htn_test_estimated_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalclinicalreviewbaseline",
            name="dm_test_estimated_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_test_estimated_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalclinicalreviewbaseline",
            name="htn_test_estimated_datetime",
        ),
        migrations.AddField(
            model_name="clinicalreviewbaseline",
            name="complications",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                help_text="If YES, complete the `Complications` CRF",
                max_length=15,
                verbose_name="Since last seen, has the patient had any complications",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicalreviewbaseline",
            name="dm_test_estimated_date",
            field=models.DateField(
                blank=True,
                help_text="calculated by the EDC using `dm_test_ago`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinicalreviewbaseline",
            name="hiv_test_estimated_date",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="calculated by the EDC using `hiv_test_ago`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinicalreviewbaseline",
            name="htn_test_estimated_date",
            field=models.DateField(
                blank=True,
                help_text="calculated by the EDC using `htn_test_ago`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreviewbaseline",
            name="complications",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                help_text="If YES, complete the `Complications` CRF",
                max_length=15,
                verbose_name="Since last seen, has the patient had any complications",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalclinicalreviewbaseline",
            name="dm_test_estimated_date",
            field=models.DateField(
                blank=True,
                help_text="calculated by the EDC using `dm_test_ago`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_test_estimated_date",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="calculated by the EDC using `hiv_test_ago`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreviewbaseline",
            name="htn_test_estimated_date",
            field=models.DateField(
                blank=True,
                help_text="calculated by the EDC using `htn_test_ago`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="dm_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete form `Diabetes Initial Review`",
                max_length=15,
                verbose_name="Have you ever been diagnosed with Diabetes",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="hiv_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete form `HIV Initial Review`",
                max_length=15,
                verbose_name="Has the patient ever tested <U>positive</U> for HIV infection?",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="hiv_test_date",
            field=models.DateField(
                blank=True,
                help_text="IF HIV(+), DATE PATIENT FIRST TESTED POSITIVE. ",
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Date of patient's most recent HIV test?",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="htn_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete form `Hypertension Initial Review`",
                max_length=15,
                verbose_name="Has the patient ever been diagnosed with Hypertension",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="dm_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete form `Diabetes Initial Review`",
                max_length=15,
                verbose_name="Have you ever been diagnosed with Diabetes",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete form `HIV Initial Review`",
                max_length=15,
                verbose_name="Has the patient ever tested <U>positive</U> for HIV infection?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_test_date",
            field=models.DateField(
                blank=True,
                help_text="IF HIV(+), DATE PATIENT FIRST TESTED POSITIVE. ",
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Date of patient's most recent HIV test?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="htn_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete form `Hypertension Initial Review`",
                max_length=15,
                verbose_name="Has the patient ever been diagnosed with Hypertension",
            ),
        ),
    ]
