# Generated by Django 4.1.2 on 2022-11-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_dx_review", "0001_initial"),
        (
            "intecomm_subject",
            "0004_remove_clinicalreviewbaseline_dm_test_estimated_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalreview",
            name="dm_reason",
            field=models.ManyToManyField(
                blank=True,
                related_name="dm_reason",
                to="edc_dx_review.reasonsfortesting",
                verbose_name="Why was the patient tested for diabetes?",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreview",
            name="hiv_reason",
            field=models.ManyToManyField(
                blank=True,
                related_name="hiv_test_reason",
                to="edc_dx_review.reasonsfortesting",
                verbose_name="Why was the patient tested for HIV infection?",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreview",
            name="htn_reason",
            field=models.ManyToManyField(
                blank=True,
                related_name="htn_test_reason",
                to="edc_dx_review.reasonsfortesting",
                verbose_name="Why was the patient tested for hypertension?",
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="reason",
            field=models.ManyToManyField(
                blank=True,
                to="edc_dx_review.reasonsfortesting",
                verbose_name="Why was the patient tested?",
            ),
        ),
    ]
