# Generated by Django 4.1.7 on 2023-04-06 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_subject", "0025_rename_med_start_ago_dminitialreview_rx_init_ago_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dminitialreview",
            old_name="med_start_date_estimated",
            new_name="rx_init_date_is_estimated",
        ),
        migrations.RenameField(
            model_name="dminitialreview",
            old_name="med_start_estimated_date",
            new_name="rx_init_calculated_date",
        ),
        migrations.RenameField(
            model_name="hivinitialreview",
            old_name="arv_initiation_date_estimated",
            new_name="rx_init_date_is_estimated",
        ),
        migrations.RenameField(
            model_name="hivinitialreview",
            old_name="arv_initiation_estimated_date",
            new_name="rx_init_calculated_date",
        ),
        migrations.RenameField(
            model_name="hivinitialreview",
            old_name="dx_estimated_date",
            new_name="dx_calculated_date",
        ),
        migrations.RenameField(
            model_name="htninitialreview",
            old_name="dx_estimated_date",
            new_name="dx_calculated_date",
        ),
        migrations.RenameField(
            model_name="historicalhivinitialreview",
            old_name="arv_initiation_date_estimated",
            new_name="rx_init_date_is_estimated",
        ),
        migrations.RenameField(
            model_name="historicalhivinitialreview",
            old_name="arv_initiation_estimated_date",
            new_name="rx_init_calculated_date",
        ),
        migrations.RenameField(
            model_name="historicalhtninitialreview",
            old_name="med_start_date",
            new_name="rx_init_date",
        ),
        migrations.RenameField(
            model_name="historicalhtninitialreview",
            old_name="med_start_estimated_date",
            new_name="rx_init_calculated_date",
        ),
        migrations.RenameField(
            model_name="htninitialreview",
            old_name="med_start_date",
            new_name="rx_init_date",
        ),
        migrations.RenameField(
            model_name="htninitialreview",
            old_name="med_start_estimated_date",
            new_name="rx_init_calculated_date",
        ),
        migrations.RenameField(
            model_name="historicaldminitialreview",
            old_name="med_start_date_estimated",
            new_name="rx_init_date_is_estimated",
        ),
    ]
