# Generated by Django 4.2.3 on 2023-07-12 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_subject", "0055_rename_drugrefilldm_return_in_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drugrefilldm",
            name="rx_days",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(186),
                ],
                verbose_name="Number of days of medication prescribed?",
            ),
        ),
        migrations.AlterField(
            model_name="drugrefillhiv",
            name="rx_days",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(186),
                ],
                verbose_name="Number of days of medication prescribed?",
            ),
        ),
        migrations.AlterField(
            model_name="drugrefillhtn",
            name="rx_days",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(186),
                ],
                verbose_name="Number of days of medication prescribed?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldrugrefilldm",
            name="rx_days",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(186),
                ],
                verbose_name="Number of days of medication prescribed?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldrugrefillhiv",
            name="rx_days",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(186),
                ],
                verbose_name="Number of days of medication prescribed?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldrugrefillhtn",
            name="rx_days",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(186),
                ],
                verbose_name="Number of days of medication prescribed?",
            ),
        ),
    ]
