# Generated by Django 4.2.3 on 2023-08-07 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_subject", "0093_alter_healtheconomicsproperty_land_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healtheconomicsproperty",
            name="land_surface_area",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999999999),
                ],
                verbose_name="Surface area",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsproperty",
            name="land_surface_area",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999999999),
                ],
                verbose_name="Surface area",
            ),
        ),
    ]
