# Generated by Django 5.0.4 on 2024-04-16 22:44

import edc_model_fields.fields.custom_django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_subject", "0175_remove_careseekinga_wait_duration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="careseekingb",
            old_name="seek_advice",
            new_name="accessed_care",
        ),
        migrations.RenameField(
            model_name="careseekingb",
            old_name="seek_facility",
            new_name="care_facility",
        ),
        migrations.RenameField(
            model_name="careseekingb",
            old_name="seek_facility_other",
            new_name="care_facility_other",
        ),
        migrations.RenameField(
            model_name="careseekingb",
            old_name="seek_care_type",
            new_name="care_type",
        ),
        migrations.RenameField(
            model_name="careseekingb",
            old_name="ill_month",
            new_name="needed_care",
        ),
        migrations.RenameField(
            model_name="careseekingb",
            old_name="no_seek_advice",
            new_name="no_accessed_care",
        ),
        migrations.RenameField(
            model_name="careseekingb",
            old_name="no_seek_advice_other",
            new_name="no_accessed_care_other",
        ),
        migrations.RenameField(
            model_name="historicalcareseekingb",
            old_name="seek_advice",
            new_name="accessed_care",
        ),
        migrations.RenameField(
            model_name="historicalcareseekingb",
            old_name="seek_facility",
            new_name="care_facility",
        ),
        migrations.RenameField(
            model_name="historicalcareseekingb",
            old_name="seek_facility_other",
            new_name="care_facility_other",
        ),
        migrations.RenameField(
            model_name="historicalcareseekingb",
            old_name="seek_care_type",
            new_name="care_type",
        ),
        migrations.RenameField(
            model_name="historicalcareseekingb",
            old_name="ill_month",
            new_name="needed_care",
        ),
        migrations.RenameField(
            model_name="historicalcareseekingb",
            old_name="no_seek_advice",
            new_name="no_accessed_care",
        ),
        migrations.RenameField(
            model_name="historicalcareseekingb",
            old_name="no_seek_advice_other",
            new_name="no_accessed_care_other",
        ),
        migrations.AlterField(
            model_name="careseekingb",
            name="accompany",
            field=edc_model_fields.fields.custom_django_fields.CharField2(
                choices=[
                    ("alone", "No one, I came alone"),
                    ("main_earner", "Main household earner"),
                    ("adult", "Other family member/relatives/friends (adults)"),
                    ("child", "Other family member/relatives/friends (children)"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=25,
                metadata="FOUTACMP1",
                null=True,
                verbose_name="Who accompanied you here today?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcareseekingb",
            name="accompany",
            field=edc_model_fields.fields.custom_django_fields.CharField2(
                choices=[
                    ("alone", "No one, I came alone"),
                    ("main_earner", "Main household earner"),
                    ("adult", "Other family member/relatives/friends (adults)"),
                    ("child", "Other family member/relatives/friends (children)"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=25,
                metadata="FOUTACMP1",
                null=True,
                verbose_name="Who accompanied you here today?",
            ),
        ),
    ]
