from edc_sites.single_site import SingleSite

fqdn = "intecomm.clinicedc.org"

all_sites = {
    "uganda": (
        SingleSite(
            101,
            "kasangati",
            country_code="ug",
            country="uganda",
            domain=f"kasangati.ug.{fqdn}",
        ),
        SingleSite(
            102,
            "Kisugu",
            country_code="ug",
            country="uganda",
            domain=f"kisugu.ug.{fqdn}",
        ),

        SingleSite(
            103,
            "kiswa",
            country_code="ug",
            country="uganda",
            domain=f"kiswa.ug.{fqdn}",
        ),
        SingleSite(
            104,
            "kyazanga",
            country_code="ug",
            country="uganda",
            domain=f"kyazanga.ug.{fqdn}",
        ),
        SingleSite(
            105,
            "mpigi",
            country_code="ug",
            country="uganda",
            domain=f"mpigi.ug.{fqdn}",
        ),
        SingleSite(
            106,
            "namayumba",
            country_code="ug",
            country="uganda",
            domain=f"namayumba.ug.{fqdn}",
        ),
        SingleSite(
            107,
            "namulonge",
            country_code="ug",
            country="uganda",
            domain=f"namulonge.ug.{fqdn}",
        ),

        SingleSite(
            108,
            "ndejje",
            country_code="ug",
            country="uganda",
            domain=f"ndejje.ug.{fqdn}",
        ),
        SingleSite(
            109,
            "sekiwunga",
            country_code="ug",
            country="uganda",
            domain=f"sekiwunga.ug.{fqdn}",
        ),
        SingleSite(
            110,
            "wakiso",
            country_code="ug",
            country="uganda",
            domain=f"wakiso.ug.{fqdn}",
        ),
    ),
    "tanzania": (
        SingleSite(
            201,
            "amana",
            title="Amana Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"amana.tz.{fqdn}",
        ),
        SingleSite(
            202,
            "bagamoyo",
            title="Bagamoyo Regional Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"bagamoyo.tz.{fqdn}",
        ),
        SingleSite(
            203,
            "rugambwa",
            title="Cardinal Rugambwa Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"rugambwa.tz.{fqdn}",
        ),
        SingleSite(
            204,
            "hindu_mandal",
            title="Hindu Mandal Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"hindu-mandal.tz.{fqdn}",
        ),
        SingleSite(
            205,
            "kisarawe",
            title="Kisarawe District Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"kisarawe.tz.{fqdn}",
        ),
        SingleSite(
            206,
            "mbagala",
            title="Mbagala Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"mbagala.tz.{fqdn}",
        ),
        SingleSite(
            207,
            "mnazi_moja",
            title="Mnazi Moja Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"mnazi.tz.{fqdn}",
        ),
        SingleSite(
            208,
            "mwananyamala",
            title="Mwananyamala Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"mwananyamala.tz.{fqdn}",
        ),
        SingleSite(
            209,
            "sinza",
            title="Sinza Hospital",
            country_code="tz",
            country="tanzania",
            domain=f"sinza.tz.{fqdn}",
        ),
        SingleSite(
            210,
            "temeke",
            title="Temeke Hospital",
            country="tanzania",
            country_code="tz",
            domain=f"temeke.tz.{fqdn}",
        ),
    ),
}
