# Generated by Django 4.1.2 on 2022-11-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_prn", "0002_remove_endofstudy_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprotocolincident",
            name="reasons_withdrawn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protocolincident",
            name="reasons_withdrawn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalprotocolincident",
            name="report_status",
            field=models.CharField(
                choices=[
                    ("open", "Open. Some information is still pending."),
                    ("closed", "Closed. This report is complete"),
                    (
                        "withdrawn",
                        "Withdrawn. This report has been withdrawn after review with investigators",
                    ),
                ],
                max_length=25,
                verbose_name="What is the status of this report?",
            ),
        ),
        migrations.AlterField(
            model_name="protocolincident",
            name="report_status",
            field=models.CharField(
                choices=[
                    ("open", "Open. Some information is still pending."),
                    ("closed", "Closed. This report is complete"),
                    (
                        "withdrawn",
                        "Withdrawn. This report has been withdrawn after review with investigators",
                    ),
                ],
                max_length=25,
                verbose_name="What is the status of this report?",
            ),
        ),
    ]
