# Generated by Django 4.1.2 on 2022-11-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_prn", "0002_communitycarelocation_patientgroupappointment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientgroupmeeting",
            old_name="patient_logs",
            new_name="patients",
        ),
    ]
