# Generated by Django 4.1.2 on 2022-11-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_prn", "0003_rename_patient_logs_patientgroupmeeting_patients"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientgroupappointment",
            name="appt_status",
            field=models.CharField(
                choices=[
                    ("new", "Not started"),
                    ("in_progress", "In Progress"),
                    ("incomplete", "Incomplete"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=25,
            ),
        ),
    ]
