# Generated by Django 4.2.1 on 2023-07-06 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_prn", "0007_alter_losstofollowup_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="endofstudy",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "End of Study",
                "verbose_name_plural": "End of Study",
            },
        ),
    ]
