# Generated by Django 4.2.10 on 2024-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_prn", "0016_alter_endofstudy_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectlocator",
            name="consent_model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsubjectlocator",
            name="consent_version",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
