# Generated by Django 6.0 on 2025-01-30 01:56

import edc_sites.managers
import edc_visit_schedule.model_mixins.on_schedule_model_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_prn", "0017_alter_historicalsubjectlocator_consent_model_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="onschedulecomm",
            managers=[
                ("on_site", edc_sites.managers.CurrentSiteManager()),
                (
                    "objects",
                    edc_visit_schedule.model_mixins.on_schedule_model_mixin.OnScheduleManager(),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="onscheduleinte",
            managers=[
                ("on_site", edc_sites.managers.CurrentSiteManager()),
                (
                    "objects",
                    edc_visit_schedule.model_mixins.on_schedule_model_mixin.OnScheduleManager(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicalsubjectlocator",
            name="may_call_work",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                verbose_name="Has the participant given permission to be contacted <b>at work</b>, by telephone or cell, by study staff for follow-up purposes during the study? ",
            ),
        ),
    ]
