# Generated by Django 4.2.11 on 2024-07-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_reports", "0005_vl_vlsummary"),
    ]

    operations = []
