# Generated by Django 5.0.8 on 2024-08-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_reports", "0010_alter_missingvldrawdates_managers"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingvldrawdates",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="sites.site"
            ),
        ),
        migrations.AlterField(
            model_name="vlsummary",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="sites.site"
            ),
        ),
        migrations.AlterField(
            model_name="vlsummary2",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="sites.site"
            ),
        ),
    ]
