# Generated by Django 4.2.3 on 2023-08-10 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("intecomm_group", "0001_initial"),
        ("intecomm_lists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0002_alter_domain_unique"),
        ("intecomm_screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientgroupmeeting",
            name="patients",
            field=models.ManyToManyField(
                to="intecomm_screening.patientlog", verbose_name="Patients"
            ),
        ),
        migrations.AddField(
            model_name="patientgroupmeeting",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="patientgroupappointment",
            name="community_care_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="intecomm_group.communitycarelocation",
            ),
        ),
        migrations.AddField(
            model_name="patientgroupappointment",
            name="patient_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="intecomm_group.patientgroup"
            ),
        ),
        migrations.AddField(
            model_name="patientgroupappointment",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="dm_patients",
            field=models.ManyToManyField(
                blank=True,
                related_name="dm_patients",
                to="intecomm_screening.patientlog",
                verbose_name="DM-only",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="hiv_patients",
            field=models.ManyToManyField(
                blank=True,
                related_name="hiv_patients",
                to="intecomm_screening.patientlog",
                verbose_name="HIV-only",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="htn_patients",
            field=models.ManyToManyField(
                blank=True,
                related_name="htn_patients",
                to="intecomm_screening.patientlog",
                verbose_name="HTN-only",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="multi_patients",
            field=models.ManyToManyField(
                blank=True,
                related_name="multi_patients",
                to="intecomm_screening.patientlog",
                verbose_name="Multi-morbidity",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="patients",
            field=models.ManyToManyField(
                blank=True, to="intecomm_screening.patientlog", verbose_name="Patients"
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="patientfollowupcall",
            name="patient_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="intecomm_screening.patientlog"
            ),
        ),
        migrations.AddField(
            model_name="patientfollowupcall",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientfollowupcall",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientfollowupcall",
            name="patient_log",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="intecomm_screening.patientlog",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientfollowupcall",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="communitycarelocation",
            name="location_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="intecomm_lists.locationtypes"
            ),
        ),
        migrations.AddField(
            model_name="communitycarelocation",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.site",
            ),
        ),
    ]
