# Generated by Django 4.1.2 on 2022-11-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_screening", "0002_alter_historicalpatientlog_patient_group_and_more"),
        ("intecomm_group", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientLog",
        ),
        migrations.AlterField(
            model_name="patientgroup",
            name="patients",
            field=models.ManyToManyField(
                blank=True, to="intecomm_screening.patientlog", verbose_name="Membership"
            ),
        ),
    ]
