# Generated by Django 4.1.2 on 2022-11-18 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_group", "0003_delete_patientlog_alter_patientgroup_patients"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="group_identifier_as_pk",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="group_identifier_as_pk",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
