# Generated by Django 4.1.2 on 2022-11-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_group", "0004_historicalpatientgroup_group_identifier_as_pk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="enforce_group_size_min",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Enforce group size minimum",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="enforce_ratio",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Enforce 2:1 NCD:HIV ratio",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="enforce_group_size_min",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Enforce group size minimum",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="enforce_ratio",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Enforce 2:1 NCD:HIV ratio",
            ),
        ),
    ]
