# Generated by Django 4.1.2 on 2022-11-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intecomm_group", "0005_historicalpatientgroup_enforce_group_size_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientgroup",
            name="confirm_randomize_now",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="If YES, please confirm by typing the wors RANDOMIZE here",
            ),
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="confirm_randomize_now",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="If YES, please confirm by typing the wors RANDOMIZE here",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientgroup",
            name="randomize_now",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Randomize now?",
            ),
        ),
        migrations.AlterField(
            model_name="patientgroup",
            name="randomize_now",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Randomize now?",
            ),
        ),
    ]
