# Generated by Django 4.1.7 on 2023-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_group", "0012_alter_historicalpatientgroup_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("recruiting", "Recruiting"),
                    ("COMPLETE", "Complete/Ready"),
                    ("in_followup", "In followup"),
                    ("dissolved", "Dissolved"),
                ],
                default="recruiting",
                help_text="Will revert to 'Recruiting' if changes are made to the list of selected patients",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="patientgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("recruiting", "Recruiting"),
                    ("COMPLETE", "Complete/Ready"),
                    ("in_followup", "In followup"),
                    ("dissolved", "Dissolved"),
                ],
                default="recruiting",
                help_text="Will revert to 'Recruiting' if changes are made to the list of selected patients",
                max_length=25,
            ),
        ),
    ]
